-- MySQL Script generated by MySQL Workbench
-- 11/26/14 15:30:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema trip_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trip_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trip_shop` DEFAULT CHARACTER SET latin1 ;
USE `trip_shop` ;

-- -----------------------------------------------------
-- Table `trip_shop`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_shop`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `tipo_usuario` INT(11) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trip_shop`.`carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_shop`.`carros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `cor` VARCHAR(45) NULL DEFAULT NULL,
  `placa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `trip_shop`.`festas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_shop`.`festas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `casa` VARCHAR(50) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `preco` VARCHAR(50) NOT NULL,
  `festa_atracao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trip_shop`.`hoteis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_shop`.`hoteis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `estrelas` INT(11) NULL DEFAULT NULL,
  `quartos` INT(11) NULL DEFAULT NULL,
  `quartos_vagos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `trip_shop`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_shop`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `cep` INT(11) NOT NULL,
  `rg` INT(11) NOT NULL,
  `cpf` VARCHAR(50) NOT NULL,
  `id_sistema` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  UNIQUE INDEX `id_sistema` (`id_sistema` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trip_shop`.`voos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_shop`.`voos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_voo` VARCHAR(30) NOT NULL,
  `data_voo` DATE NOT NULL,
  `horario_voo` TIME NOT NULL,
  `qtd_passagens` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_voo` (`numero_voo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
